# Generated by Django 4.1 on 2023-08-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_sale_ic_number_alter_sale_postal_code_and_more'),
    ]

