# Generated by Django 4.1 on 2023-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='costs',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
