# Generated by Django 4.1 on 2023-08-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_item_image_alter_item_costs'),
        ('api', '0022_alter_item_costs'),
    ]

    operations = [
    ]
