# Generated by Django 4.1 on 2023-08-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20230805_2103'),
    ]

    operations = [

    ]
