# Generated by Django 4.1 on 2023-08-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_item_image'),
    ]

    operations = [
      
    ]
